### ISSUE TITLE
OS X doesn't seem to have "endian.h"

### ISSUE THREAD

**Issue by geoffleyland** [mbalmer/luapgsql#19]
Adding this in luapgsql.c is a bit tacky, but it gets it to compiling and building:

    #ifdef __APPLE__
      #include <libkern/OSByteOrder.h>
      #define htobe64(x) OSSwapHostToBigInt64(x)
    #else
      #include <endian.h>
    #endif

I can fork and make a pull request if you like, but this is pretty minor.

**Comment by mbalmer** [comment]
Added that, thanks!

**Comment by yuangu** [comment]
#elif _WIN32
#include <winsock2.h>
#define htobe64(x) htonll(x)
#endif

for windows。

**Comment by mbalmer** [comment]
this topic is closed, please open a new issue and provide a source code patch.
