### ISSUE TITLE
Missing braces in conn_prepare

### ISSUE THREAD

**Issue by geoffleyland** [mbalmer/luapgsql#20]
It looks like lines 504-508 in luapgsql.c should be:

	for (n = 0, sqlParams = 0; n < nParams; n++) {
		get_sql_params(L, 4 + n, sqlParams, NULL, NULL, NULL, NULL,
		    &count);
		sqlParams += count;
    }

(that is, the curly braces are missing)

**Comment by mbalmer** [comment]
Fixed, also in some more locations, sigh...  Thanks!
