### ISSUE TITLE
Lua 5.3 support

### ISSUE THREAD

**Issue by daurnimator** [mbalmer/luapgsql#21]
I tested out 5.3 support today, worked at a basic level by merely adding `-DLUA_COMPAT_APIINTCASTS` to `CFLAGS`.
The reason for this is the removal of `luaL_checkint`, use `luaL_checkinteger` instead.

For complete support, I think the only other thing would be supporting 64bit ints in `get_sql_params` in `LUA_TNUMBER` case:
   - check `lua_isinteger`, if true:
   - `paramTypes[n] = INT8OID;`
   -  `*(uint64_t *)paramValues[n] = htobe64(lua_tointeger(L, t))`

**Comment by mbalmer** [comment]
Like this:

Index: luapgsql.c
===================================================================
--- luapgsql.c	(Revision 6401)
+++ luapgsql.c	(Arbeitskopie)
@@ -353,7 +353,12 @@
 		break;
 	case LUA_TNUMBER:
 		if (paramTypes != NULL)
-			paramTypes[n] = FLOAT8OID;
+#if LUA_VERSION_NUM >= 503
+			if (lua_isinteger(L, t))
+				paramType[n] = INT8OID;
+			else
+#endif
+				paramTypes[n] = FLOAT8OID;
 		if (paramValues != NULL) {
 			union {
 				double v;
@@ -360,7 +365,12 @@
 				uint64_t i;
 			} swap;
 
-			swap.v = lua_tonumber(L, t);
+#if LUA_VERSION_NUM >= 503
+			if (lua_isinteger(L, t))
+				swap.i = lua_tointeger(L, t);
+			else
+#endif
+				swap.v = lua_tonumber(L, t);
 			paramValues[n] = malloc(sizeof(uint64_t));
 			if (paramValues[n] == NULL)
 				return -1;
@@ -1226,7 +1236,7 @@
 {
 	lua_pushstring(L,
 	    PQfname(*(PGresult **)luaL_checkudata(L, 1, RES_METATABLE),
-	    luaL_checkint(L, 2) - 1));
+	    luaL_checkinteger(L, 2) - 1));
 	return 1;
 }
 
@@ -1306,7 +1316,7 @@
 {
 	lua_pushstring(L,
 	    PQgetvalue(*(PGresult **)luaL_checkudata(L, 1, RES_METATABLE),
-	    luaL_checkint(L, 2) - 1, luaL_checkint(L, 3) - 1));
+	    luaL_checkinteger(L, 2) - 1, luaL_checkinteger(L, 3) - 1));
 	return 1;
 }
 
@@ -1315,7 +1325,7 @@
 {
 	lua_pushboolean(L,
 	    PQgetisnull(*(PGresult **)luaL_checkudata(L, 1, RES_METATABLE),
-	    luaL_checkint(L, 2) - 1, luaL_checkint(L, 3) - 1));
+	    luaL_checkinteger(L, 2) - 1, luaL_checkinteger(L, 3) - 1));
 	return 1;
 }
 
@@ -1324,7 +1334,7 @@
 {
 	lua_pushinteger(L,
 	    PQgetlength(*(PGresult **)luaL_checkudata(L, 1, RES_METATABLE),
-	    luaL_checkint(L, 2) - 1, luaL_checkint(L, 3) - 1));
+	    luaL_checkinteger(L, 2) - 1, luaL_checkinteger(L, 3) - 1));
 	return 1;
 }

**Comment by mbalmer** [comment]
Thanks, changed it accordingly, but could not yet test it on a 5.3 Lua (no regression on 5.2, though).

**Comment by daurnimator** [comment]
I saw you breifly post the diff here and delete it (probably due to messed up formatting, surround in \`\`\`diff\npaste here\n\`\`\` to get monospaced and syntax highlighted on github).

Comment on that diff:
  - I'm not sure if `swap.i = lua_tointeger(L, t);` results in loss of precision? or might have undefined behaviour on overflow? I'd have to check the C standard here...
  - Remember to `#define INT8OID`
  - Update to rockspec to say you support 5.3 under 'dependencies': `"lua >= 5.1";`

**Comment by mbalmer** [comment]
afaict, swap.i and the value returned by lua_tointeger are of the same size. The other issues have been addressed.

**Comment by daurnimator** [comment]
>afaict, swap.i and the value returned by lua_tointeger are of the same size.

Yep. Just I wasn't sure what would happen as lhs is unsigned, rhs is signed. 

> The other issues have been addressed.

Yes, Thankyou. 
I haven't tested it out yet though.
